-- SAQR MEDIA standalone schema. Run in Supabase SQL editor.
create extension if not exists pgcrypto;
create table if not exists categories(id text primary key, name text not null, slug text unique, icon text, description text, display_order int default 0, published boolean default true, data jsonb default '{}'::jsonb);
create table if not exists services(id text primary key, name text not null, slug text unique, category_id text references categories(id), category_slug text, short_description text, description text, long_description text, price_type text default 'custom', fixed_price numeric, min_price numeric, max_price numeric, currency text default 'IQD', unit text, minimum_quantity numeric, maximum_quantity numeric, delivery_time text, image_url text, gallery jsonb default '[]', video_url text, audio_url text, icon text, badges jsonb default '[]', benefits jsonb default '[]', faq jsonb default '[]', guarantee text, is_free boolean default false, is_gift boolean default false, free_starts_at timestamptz, free_ends_at timestamptz, is_fast boolean default false, is_new boolean default false, is_most_requested boolean default false, is_featured boolean default false, orders_count int default 0, published boolean default true, is_active boolean default true, sort_order int default 0, seo_title text, seo_description text, og_image text, data jsonb default '{}'::jsonb, updated_at timestamptz default now());
create table if not exists products(id text primary key, name text not null, slug text unique, description text, price numeric, image_url text, category text, subscription_duration text, stock numeric default -1, status text default 'published', data jsonb default '{}'::jsonb);
create table if not exists platforms(id text primary key, key text unique, name text, url text, icon text, color text, active boolean default true, sort_order int default 0, data jsonb default '{}'::jsonb);
create table if not exists payment_methods(id text primary key, key text unique, name text, account_name text, account_number text, phone text, instructions text, qr text, logo text, enabled boolean default true, sort_order int default 0, data jsonb default '{}'::jsonb);
create table if not exists news(id text primary key, title text, body text, link text, cover_url text, gallery jsonb default '[]', video_url text, audio_url text, published boolean default true, published_at timestamptz, data jsonb default '{}'::jsonb);
create table if not exists daily_tips(id text primary key, title text, body text, category text, image_url text, video_url text, audio_url text, cta text, published boolean default true, published_at timestamptz, data jsonb default '{}'::jsonb);
create table if not exists media_assets(id text primary key, type text, url text, thumbnail text, alt_text text, service_id text, product_id text, project_id text, user_id text, status text, is_ai_generated boolean default false, data jsonb default '{}'::jsonb);
create table if not exists site_settings(id text primary key, brand_name text, brand_name_en text, tagline text, logo_url text, favicon_url text, hero_title text, hero_description text, primary_color text, accent_color text, whatsapp_number text, office_location text, socials jsonb default '{}'::jsonb, payment_methods jsonb default '[]', data jsonb default '{}'::jsonb);
create table if not exists offers(id text primary key, name text, slug text unique, description text, image_url text, service_ids jsonb default '[]', original_price numeric, discount_percent numeric, final_price numeric, starts_at timestamptz, ends_at timestamptz, max_orders int, published boolean default false, data jsonb default '{}'::jsonb);
create table if not exists packages(id text primary key, name text, slug text unique, description text, image_url text, service_ids jsonb default '[]', original_price numeric, discount_percent numeric, final_price numeric, published boolean default false, data jsonb default '{}'::jsonb);
create table if not exists courses(id text primary key, name text, slug text unique, description text, price numeric, min_price numeric, max_price numeric, image_url text, video_url text, support boolean default false, published boolean default false, data jsonb default '{}'::jsonb);
create table if not exists projects(id text primary key, name text, slug text unique, description text, industry text, logo_url text, cover_url text, gallery jsonb default '[]', services jsonb default '[]', results jsonb default '[]', links jsonb default '{}', client_review text, status text default 'draft', data jsonb default '{}'::jsonb);
create table if not exists links(id text primary key, label text, url text, placement text, icon text, active boolean default true, sort_order int default 0, data jsonb default '{}'::jsonb);
create table if not exists notifications(id text primary key, title text, body text, type text, link text, published boolean default true, data jsonb default '{}'::jsonb);
create table if not exists orders(id uuid primary key default gen_random_uuid(), customer_name text, project_name text, area text, note text, payment_method text, total numeric default 0, status text default 'new', items jsonb default '[]', attachments jsonb default '[]', created_at timestamptz default now());
-- RLS baseline: public read for published catalog, authenticated writes should be restricted with your admin role policy.
alter table categories enable row level security; alter table services enable row level security; alter table products enable row level security; alter table platforms enable row level security; alter table payment_methods enable row level security; alter table news enable row level security; alter table daily_tips enable row level security;
create policy "public read categories" on categories for select using (published=true);
create policy "public read services" on services for select using (published=true and is_active=true);
create policy "public read products" on products for select using (status='published');
create policy "public read platforms" on platforms for select using (active=true);
create policy "public read payment methods" on payment_methods for select using (enabled=true);
create policy "public read news" on news for select using (published=true);
create policy "public read tips" on daily_tips for select using (published=true);
